### ISSUE TITLE
BaseModule abstract class

### ISSUE THREAD

**Issue by Nitr4x** [hydrabus-framework/framework#10]
It would be relevant to change your BaseModule class name. Indeed, your class is an abstract class and should be named **ASomething** to respect this design pattern.

Moreover, I advice you to use the python abstract class definition to ensure that your run method will be overwritted by your child module.

**Comment by ghecko** [comment]
Done in commit [#05110c3](https://github.com/hydrabus-framework/framework/commit/05110c39e3de0a90f59202bb16659be2e7a4f2e0)
